### PR TITLE
';--have i been pwned?

### PR DESCRIPTION
**Pull request by richardhj**
Adds a new validator.

### CODE REVIEW

**Review by Toflar — CHANGES_REQUESTED** [review]
Nice one! Can't we re-use the Symfony `NotCompromisedPassword` validator logic here maybe? Or at least use the Symfony HttpClient rather than Guzzle?

**Comment by richardhj** [comment]
NotCompromisedPassword is only available in Symfony >= 4.3: https://symfony.com/doc/current/reference/constraints/NotCompromisedPassword.html

There is one package that would reduce things but it comes with a lot of dependencies: https://packagist.org/packages/divineomega/password_exposed

Changing to HttpClient is reasonable.

**Comment by Toflar** [comment]
HttpClient is Symfony 4.3+ too.

**Comment by richardhj** [comment]
Ooops. I guess it is not possible to raise dependencies. The extension is used in Contao 4.4 projects.

**Comment by richardhj** [comment]
I checked the `NotCompromisedPasswordValidator`. The validators are quite similar but there is no improvement to take along :-)

**Comment by aschempp** [comment]
As this is a new feature, it will require a new minor version anyway. And a new minor version might raise the Contao minimum support …

**Comment by aschempp** [comment]
@richardhj any plans to finish this, for Contao 4.9 only should be sufficient? Or should we close the PR? 😊

**Comment by richardhj** [comment]
I will update this PR :)

**Pull request merged**
